Repository OSCPS-Project/OSCPS, pull requests merged in 2024-12, with the labels that each got.

#24 Fix thermo test fail
  oscps-gui/Cargo.toml
  oscps-gui/src/main.rs
  oscps-lib/src/component.rs
  oscps-lib/src/thermodynamics.rs
Labels: bug

#27 Readme update
  README.md
Labels: documentation

#25 Linter fix
  oscps-lib/src/blocks.rs
  oscps-lib/src/component.rs
  oscps-lib/src/connector.rs
Labels: Linter-Improvement
